version: "3.8"
services:
  backend:
    image: "sghanti03/springboot-react-fullstack:7.7.2023.15.35.31"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev