version: "3.8"
services:
  backend:
    image: "sghanti03/springboot-react-fullstack:9.7.2023.16.1.2"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev