version: "3.8"
services:
  backend:
    image: "sghanti03/springboot-react-fullstack:8.7.2023.6.42.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev